version: '3.8'

services:
  app:
    image: nginx:1.18
    ports:
      - '80:80'
    volumes:
      - ./conf/app/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - phpfpm
    hostname: app.magento
  
  phpfpm:
    build: ./docker/phpfpm
    volumes:
      - ./src:/var/www/html
  
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
      - MYSQL_ROOT_PASSWORD=magento
    volumes:
      - ./mysql:/var/lib/mysql
    hostname: mysql.magento
  
  elasticsearch:
    image: elasticsearch:7.17.0
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    hostname: elastic.magento

  redis:
    image: redis:6.2
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=rabbit
    hostname: rabbitmq.magento
        